memberdictionary = {
    'admin': [
        {
            'number': 'MAD-001',
            'name': 'Elijah Q. Boncay',
            'course': 'Bachelor of Public Administration',
            'year': 3,
            'role': 'President',
            'bio': 'A third-year student completing my undergraduate degree in Public Administration in a state-run university in the country. I am a former Supreme Student Government (SSG) president in high school, chairperson of the Pasig City Youth Development Council – Education Committee, and currently serving as the Head Executive of Niig, a youth-led volunteer organization in Pasig City.',
            'email': 'elijahqboncay1617@gmail.com',
            'fblink': 'https://www.facebook.com/elijah.boncay',
        },
        {
            'number': 'MAD-002',
            'name': 'Patricia Kyle Rombaon',
            'course': 'Bachelor of Science in Community Development',
            'year': 3,
            'role': 'Vice President',
            'bio': 'I am currently a 3rd-year student taking up B.S Community Development in the University of the Philippines, Diliiman. I am also a member of Junior Philippine Geographical Society - UP Diliman that tackles socio-academic related events. And I also believe in the saying by A.D. Aliwat, In Limbo that “People deserve the benefit of the doubt, but information? Always hold it up to a cold white light. Misinformation is a tool of the devil”.',
            'email': 'prombaon@gmail.com',
            'fblink': 'https://www.facebook.com/ptrcrmbn',
        },         
        {
            'number': 'MAD-22-003',
            'name': 'Rochelle Ayroso',
            'course': 'Bachelor of Science in Library and Information Science',
            'year': 1,
            'role': 'Secretary',
            'bio': 'I am a first year student studying Library and Information Science. I was previously a member of my high school’s student council media team, as well as a former math club and science club member. I am an observant and detail-oriented person who is also approachable and tries their best to assist others when needed.',
            'email': 'rjmayroso@gmail.com',
            'fblink': 'https://www.facebook.com/cat.pebble/',
        },
        {
            'number': 'MAD-22-004',
            'name': 'Jolly Calixtro',
            'course': 'Bachelor of Science in Library and Information Science',
            'year': 1,
            'role': 'Treasurer',
            'bio': 'I am an undergraduate student in a CHED-Center of Excellence institution taking up a DOST-recognized program aligned with the integration of web development and management of different information repositories. I am the former Student Council President of San Lorenzo Ruiz Senior High School and Associate Editor-in-Chief of Ang Daloy, the official student publication of Santolan High School.',
            'email': 'jollygonzales483@gmail.com',
            'fblink': 'https://www.facebook.com/jgcalixtro26',
        },
        {
            'number': 'MAD-22-005',
            'name': 'Sammy Rombaon',
            'course': 'Bachelor of Science in Library and Information Science',
            'year': 1,
            'role': 'Head of Communications',
            'bio': 'I am a first year B Library and Information Science student. I am versatile, creative and passionate about the things I am handling. I am also a performer and an influencer that shares positivity and self-appreciation to my social media pages.',
            'email': 'samrombs@gmail.com',
            'fblink': 'https://www.facebook.com/samantha/rombaon',
        },
    ]
}